services:
    rabbitmq:
        image: rabbitmq:3-management-alpine

        container_name: rabbitmq

        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:8080:15672"
            - "127.0.0.1:15672:15672"

        networks:
            - rabbitmq-hello-world

        volumes:
            - rabbitmq-hello-world-data:/var/lib/rabbitmq/
            - rabbitmq-hello-world-logs:/var/log/rabbitmq/
            
networks:
    rabbitmq-hello-world:
        driver: bridge

volumes:
    rabbitmq-hello-world-data:
    rabbitmq-hello-world-logs:

